### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by philgoetz** [jimv39/qvcsos#14]
I can't find any documentation for QVCS.
Do I need to install it before I can read the documentation?
Given that installing it requires figuring out how to compile it, I think that will prevent anyone who hasn't used it before from trying it out.
Does it not exist on the web, or as a readable file within the source download?

**Comment by jimv39** [comment]
You need to clone the repository here. The README.md file contains some guidance on getting started.

You need to have some fluency with maven, java, and postgresql to be able to get things set up. I use Apache NetBeans as my IDE... things build cleanly on that.

**Comment by philgoetz** [comment]
You're right. I don't know how I didn't see that.
