### ISSUE TITLE
Backwards compatibility and updating?

### ISSUE THREAD

**Issue by philgoetz** [jimv39/qvcsos#15]
I have a lot of projects with version control using QVCS which date back 10-20 years.
Should I install a 10-year-old version of QVCS, or the new version?
Can I use a single version for all of these projects?
Can I update an existing QVCS installation in any way simpler than uninstalling the old and installing the new?

**Comment by jimv39** [comment]
The master branch here has a version of QVCS-Enterprise that uses the same archive file format as QVCS/QVCS-Pro.

If you pull that branch, then take a look at the file: qvcse-server/src/main/resources/ServerWebSite/docs/faq.html

There is an answer there on how to migrate from QVCS/QVCS-Pro to the version of QVCS-Enterprise that is on the master branch... it's the last FAQ in that file.
