### ISSUE TITLE
A QvcsPro SCC DLL Question

### ISSUE THREAD

**Issue by nurbles** [jimv39/qvcsos#16]
My 64<>32 bit code to allow VS2022 to use QVCSPro is working ... except for a bug that I found in the QvcsScc.dll:  Instead of using the HWND passed in to the `SccUncheckout()` (and other) functions, the DLL is using a `GetParent()` function (or something like it) which results in the dialogs being hidden since my programs are designed to be invisible when VS2022 is using QVCSPro.  You shared the DLL source with me, but the project doesn't build due to quite a few missing header files (and possibly more once the code actually _compiles_.)

Is there any chance I can get the missing pieces that are necessary to re-build QVCSSCC.DLL so that I may fix this minor bug?

Sorry, to bother you about this.  I did not expect to find a bug (especially one I might actually be able to fix!) in the QvcsScc code.

**Comment by nurbles** [comment]
I seems I was wrong.  No bug.  But the hWnd that VS2022 was passing doesn't work.  I replaced it with GetDesktopWindow() and now the QVCS dialog pop to the top like they should.  Sorry to bother you.  Everything seems to be working now, so I probably won't be back here again.  Thanks for such a great product -- it worked, it was reliable, it supported all the functionality we require and it was very easy to set up and use.  Sadly, nothing else I've found manages all four.

**Comment by jimv39** [comment]
It's really hard to compete with 'free'... e.g. git, subversion, etc... which is why I shut down Quma, and went back to work. 

I've since retired. But I'm still working on the open source 'Enterprise' code base. It doesn't fit your Scc integration requirements. I'm probably the only person on the planet who uses it ;)
