### ISSUE TITLE
Build no longer works with jdk7

### ISSUE THREAD

**Issue by jnavila** [jimv39/qvcsos#2]
The readme file states otherwise.

**Comment by jimv39** [comment]
I'll have to update the readme. Thanks.

**Comment by jnavila** [comment]
Just in case, it is still possible to compile the project with jdk7 with an earlier revision, say jimv39/qvcsos@addb614 .

Btw, I was just looking for a way to revive an ooold archive. QVCS-Pro as it seems.

**Comment by jimv39** [comment]
jdk7 should work for anything at addb614 or earlier... you should be able to get things to work with Java8 also -- I haven't changed the archive file format (yet).

**Comment by jimv39** [comment]
Updated the readme to say that JDK 8 is now the minimum for the develop branch.
