### ISSUE TITLE
Pre-compiled Download Links

### ISSUE THREAD

**Issue by joshualambert** [jimv39/qvcsos#3]
Hey Jim--

My name is Josh Lambert, I'm the owner of Centreville Tech. (http://centrevilletech.com). Just dropping a a line to let you know that I'd be willing to host download links for precompiled versions of this at no cost for the good of the project. I got the Mac version compiled successfully this morning on Yosemite, and can go ahead and stick this online if you're OK with that.

Let me know.

Cheers,
Josh

**Comment by joshualambert** [comment]
![qvcsyosemite](https://cloud.githubusercontent.com/assets/1421842/6510750/901906c4-c32d-11e4-8592-096b451ce0f8.png)

**Comment by jimv39** [comment]
Sounds fine to me... (Still trying to figure out the problem with java8u40).
